reinvented-stuff/tdlib-build

- .github/workflows/build_tdlib.yml
- .github/workflows/release.yml
> [Fix] Typos were indeed there. Rearranged release steps. Fetching artifacts in an easier way.

- .github/workflows/release.yml
> [Fix] Typo in variable name

- .github/workflows/release.yml
> [Fix] Redirection done poorly

- .github/workflows/build_tdlib.yml
- .github/workflows/release.yml
> [Change] Stupid YAML string folding

- .github/workflows/scheduled.yml
> [Add] Scheduled workflow with artifactory upload

- .github/workflows/scheduled.yml
> [Change] Schedule runs are now happening daily

- .github/workflows/scheduled.yml
> [Add] Fetching the last tdlib version on scheduled workflow

- .github/workflows/scheduled.yml
> [Change] Temporarily set cron schedule to once a hour

- .github/workflows/scheduled.yml
> [Change] More debug, changed schedule

- .github/workflows/scheduled.yml
> [Fix] Scheduled build notification condition was broken

- .github/workflows/scheduled.yml
> [Change] Improved message text

- .github/workflows/scheduled.yml
> [Fix] Notification send out condition was broken

- .github/workflows/build_tdlib.yml
> [Change] Attempt to make terraform show work

- .github/workflows/build_tdlib.yml
> [Change] Github Workflow security and troubleshooting facilities improvements

- .github/workflows/build_feature_branch.yml
- .github/workflows/build_tdlib.yml
- .github/workflows/release.yml
> [Add] Feature branch build. Improved notification strategy in Workflow.

- .cirrus.yml
- sbin/macos-13/build.sh
- sbin/macos-13/install-dependencies.sh
> [Add] Apple M1 builds with Cirrus-CI

- .cirrus.yml
- sbin/macos-13/build.sh
- sbin/macos-13/install-dependencies.sh
> [Add] Parallel build on Cirrus-CI for m1

- .cirrus.yml
- .github/workflows/build_tdlib.yml
- sbin/macos-13/install-dependencies-docker.sh
> [Add] Attempt to do an arm64 docker image

- .cirrus.yml
- .github/workflows/build_tdlib.yml
> [Change] Switching from artifactory to google buckets for artifact storage

- .github/workflows/release.yml
> [Fix] Release now uses the google bucket instead of Artifactory

- .github/workflows/release.yml
> [Fix] Missed redirect of the artifact list to a file

- .github/workflows/release.yml
>  [Fix] YAML markup played tricks on me 

- .github/workflows/release.yml
> [Fix] Forgot about the actual downloading

- .github/workflows/release.yml
> [Fix] Artifact filename was not crafted correctly

- infra/ansible/roles/role-linux-base/vars/rocky-8.yml
> [Add] podman-docker for rocky8

- infra/ansible/030_containers.yml
> [Fix] Containers routine fails to perform

- .github/workflows/build_tdlib.yml
> [Change] GHR Token retrival refactored

- .github/workflows/build_tdlib.yml
- .github/workflows/tear_down_runners.yml
> gh-74 [Fix] upload-artifact version bump from v3xx to v4

- .github/workflows/scheduled.yml
> gh-83 [Feature] Automated feature branch for scheduled workflow

- .github/workflows/scheduled.yml
> gh-84 [Fix] Empty CURRENT_VERSION

- .github/workflows/scheduled.yml
> gh-84 [Fix] Workflow must trigger downstream workflows

- .github/workflows/scheduled.yml
> gh-84 [Fix] Making the Build Workflow run on automated version bump
